# Generated by Django 2.2.2 on 2019-06-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='creaed_time',
            new_name='created_time',
        ),
    ]
